### ISSUE TITLE
hipo-io: automatic code generation

### ISSUE THREAD

**Issue by fbossu** [JeffersonLab/hipo_tools#11]
I found very useful the automatic code generation that is available in the hipo-io library on JLab CUE.
I see that it is commented out (from line 166 of hipo.cxx). 
Will it be restored in the near future?

**Comment by whit2333** [comment]
You got it. https://github.com/JeffersonLab/hipo_tools/pull/15

Once merged you can do something like this:
```hipo_io code -c starterCode.cxx -b REC::Track REC::Event CND::adc -i data/some_file.hipo```

This will output the banks REC::Track*, REC::Event, CND::adc.

Let me know if there is anything missing or to be added.

**Comment by whit2333** [comment]
Looks like it got pulled in.
